name: FTP Deploy on Push

on:
  push:
    branches:
    - main
  
jobs:
  web_deploy:
    name: deploy to main
    runs-on: ubuntu-latest
    steps:
    - name: Get Latest Code
      uses: actions/checkout@v2
    
    - name: Sync Files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.MAIN_FTP_SERVERNAME}}
        username: ${{ secrets.MAIN_FTP_USERNAME}}
        password: ${{ secrets.MAIN_FTP_PASSWORD}}
        server-dir: /public_html/wp-content/themes/meissa/
  
